name: Update Admin API

on:
  workflow_call:
    inputs:
      shopware_version:
        description: "Shopware version"
        required: true
        type: string


jobs:
  generate-schema:
    uses: shopware/docs-ci/.github/workflows/generate_schema.yml@main
    with:
      schema_flags: ""
      schema_file: adminapi.json
      shopware_version: ${{ inputs.shopware_version }}
    secrets: inherit
        
  open-pr:
    name: "Open a pull request"
    runs-on: ubuntu-latest
    needs: [generate-schema]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: download api schema
      uses: actions/download-artifact@v3
      with:
        name: ${{needs.generate-schema.outputs.api_schema}}

    - name: install yq
      uses: cachix/install-nix-action@v18

    - name: Add custom descriptions
      run: |
        for k in $(yq '. | keys | .[]' descriptions.yml); do
          newDescription=$(yq ".\"$k\"" descriptions.yml);
          # Indent 4; output as json; edit in place
          yq  -I 4 -o json -i "$k.description = \"${newDescription}\"" adminapi.json
        done

    - name: Prettify
      run: |
        sudo apt-get update
        sudo apt-get install -y moreutils
        jq . adminapi.json | sponge adminapi.json
      
    - name: Create PR
      uses: peter-evans/create-pull-request@v4
      with:
        add-paths: adminapi.json
        author: shopwareBot <example@example.com>
        committer: shopwareBot <example@example.com>
        assignees: sushmangupta, Isengo1989, bojanrajh
        branch: schema-update
        delete-branch: true
        title: 'Update admin API schema'
